version: "3.7"

services:
  database:
    container_name: apia_database
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
        - 5432:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
