"""initial

Revision ID: 628b4b10dc69
Revises: 
Create Date: 2024-02-07 21:29:50.294497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628b4b10dc69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('month', sa.Integer(), server_default=sa.text('EXTRACT(month FROM now())'), nullable=True),
    sa.Column('year', sa.Integer(), server_default=sa.text('EXTRACT(year FROM now())'), nullable=True),
    sa.Column('day', sa.Integer(), server_default=sa.text('EXTRACT(day FROM now())'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('user_monthly_expenses',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('month', sa.Integer(), server_default=sa.text('EXTRACT(month FROM now())'), nullable=False),
    sa.Column('year', sa.Integer(), server_default=sa.text('EXTRACT(year FROM now())'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'month', 'year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_monthly_expenses')
    op.drop_table('transactions')
    # ### end Alembic commands ###
